"""initialize migration

Revision ID: 42ebded8952f
Revises: d8772635bf76
Create Date: 2025-12-13 16:23:39.892221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ebded8952f'
down_revision = 'd8772635bf76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tableparameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_value', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tableparameter', schema=None) as batch_op:
        batch_op.drop_column('default_value')

    # ### end Alembic commands ###
