"""initialize migration

Revision ID: 684a6350bbd7
Revises: 
Create Date: 2026-09-13 12:19:55.339220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684a6350bbd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('foreign_key', 'unique', 'nullable', 'primary_key', 'default', name='validconstraints'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=True),
    sa.Column('last_public_id_created', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('api_token', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sqlite_autoincrement=True
    )
    op.create_table('api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_api_id_user_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_api_name_user_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('api', schema=None) as batch_op:
        batch_op.create_index('idx_api_id_user_id', ['id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_user_id'), ['user_id'], unique=False)

    op.create_table('user_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_rows', sa.Integer(), nullable=False),
    sa.Column('current_tables', sa.Integer(), nullable=False),
    sa.CheckConstraint('current_rows <= 2000', name='check_current_rows_not_exceed_max_rows'),
    sa.CheckConstraint('current_tables <= 100', name='check_current_tables_not_exceed_max_tables'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sqlite_autoincrement=True
    )
    op.create_table('table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'id', name='uq_table_api_id_table_id'),
    sa.UniqueConstraint('api_id', 'name', name='uq_table_api_id_table_name'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_api_id'), ['api_id'], unique=False)

    op.create_table('entrylist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_key_value', sa.Text(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'primary_key_value', name='uq_entrylist_table_id_primary_key_value'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('entrylist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrylist_table_id'), ['table_id'], unique=False)

    op.create_table('foreignkeyfieldreferencetable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id'),
    sqlite_autoincrement=True
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_ref_pk', sa.String(), nullable=False),
    sa.Column('foreign_key_rel_id', sa.Integer(), nullable=True),
    sa.Column('child_table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_table_id'], ['table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['foreign_key_rel_id'], ['foreignkeyfieldreferencetable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_ref_pk', 'foreign_key_rel_id', 'child_table_id', name='uq_relationship_entry_ref_pk_foreign_key_rel_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.create_index('idx_entry_ref_pk_foreign_key_rel_id', ['entry_ref_pk', 'foreign_key_rel_id'], unique=False)

    op.create_table('tableparameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.Enum('string', 'decimal', 'text', 'integer', 'boolean', 'date', 'datetime', name='datatypes'), nullable=False),
    sa.Column('primary_key', sa.Boolean(), nullable=True),
    sa.Column('foreign_key_reference_id', sa.Integer(), nullable=True),
    sa.Column('dataType_length', sa.Integer(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('foreign_key_default_value_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('table_level_on_delete', sa.Enum('cascade', 'protect', name='tablelevelondeleteoptions'), nullable=False),
    sa.Column('row_level_on_delete', sa.Enum('cascade', 'protect', 'set_null', name='rowlevelondeleteoptions'), nullable=False),
    sa.ForeignKeyConstraint(['foreign_key_default_value_id'], ['entrylist.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['foreign_key_reference_id'], ['foreignkeyfieldreferencetable.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='uq_tableparameter_table_id_name'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('tableparameter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tableparameter_foreign_key_reference_id'), ['foreign_key_reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tableparameter_table_id'), ['table_id'], unique=False)

    op.create_table('entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('tableparameter_id', sa.Integer(), nullable=True),
    sa.Column('entry_list_id', sa.Integer(), nullable=True),
    sa.Column('fk_entry_list_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('entry_list_id != fk_entry_list_id', name='check_fk_entry_list_id_not_same_as_entry_list_id'),
    sa.ForeignKeyConstraint(['entry_list_id'], ['entrylist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_entry_list_id'], ['entrylist.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tableparameter_id'], ['tableparameter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_entry_list_id'), ['entry_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_fk_entry_list_id'), ['fk_entry_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_tableparameter_id'), ['tableparameter_id'], unique=False)

    op.create_table('entrylist_relationships',
    sa.Column('relationship_id', sa.Integer(), nullable=True),
    sa.Column('entrylist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrylist_id'], ['entrylist.id'], name='fk_entrylist_relationships_entrylist_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], name='fk_entrylist_relationships_relationship_id', ondelete='CASCADE'),
    sa.UniqueConstraint('relationship_id', 'entrylist_id', name='uq_relationship_entrylist')
    )
    op.create_table('parameter_constraint',
    sa.Column('tableparameter_id', sa.Integer(), nullable=True),
    sa.Column('constraint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraint.id'], name='fk_parameter_constraint_constraint_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tableparameter_id'], ['tableparameter.id'], name='fk_parameter_constraint_tableparameter_id', ondelete='CASCADE'),
    sa.UniqueConstraint('tableparameter_id', 'constraint_id', name='uq_tableparameter_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_constraint')
    op.drop_table('entrylist_relationships')
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_tableparameter_id'))
        batch_op.drop_index(batch_op.f('ix_entry_fk_entry_list_id'))
        batch_op.drop_index(batch_op.f('ix_entry_entry_list_id'))

    op.drop_table('entry')
    with op.batch_alter_table('tableparameter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tableparameter_table_id'))
        batch_op.drop_index(batch_op.f('ix_tableparameter_foreign_key_reference_id'))

    op.drop_table('tableparameter')
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_index('idx_entry_ref_pk_foreign_key_rel_id')

    op.drop_table('relationship')
    op.drop_table('foreignkeyfieldreferencetable')
    with op.batch_alter_table('entrylist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrylist_table_id'))

    op.drop_table('entrylist')
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_api_id'))

    op.drop_table('table')
    op.drop_table('user_limit')
    with op.batch_alter_table('api', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_user_id'))
        batch_op.drop_index('idx_api_id_user_id')

    op.drop_table('api')
    op.drop_table('user')
    op.drop_table('constraint')
    # ### end Alembic commands ###
